INSERT INTO `nationalities` (`en_name`, `ar_name`, `id`) VALUES
('Afghan', 'أفغانستاني', 1),
('Albanian', 'ألباني', 2),
('Aland Islander', 'آلاندي', 3),
('Algerian', 'جزائري', 4),
('American Samoan', 'أمريكي سامواني', 5),
('Andorran', 'أندوري', 6),
('Angolan', 'أنقولي', 7),
('Anguillan', 'أنغويلي', 8),
('Antarctican', 'أنتاركتيكي', 9),
('Antiguan', 'بربودي', 10),
('Argentinian', 'أرجنتيني', 11),
('Armenian', 'أرميني', 12),
('Aruban', 'أوروبهيني', 13),
('Australian', 'أسترالي', 14),
('Austrian', 'نمساوي', 15),
('Azerbaijani', 'أذربيجاني', 16),
('Bahamian', 'باهاميسي', 17),
('Bahraini', 'بحريني', 18),
('Bangladeshi', 'بنغلاديشي', 19),
('Barbadian', 'بربادوسي', 20),
('Belarusian', 'روسي', 21),
('Belgian', 'بلجيكي', 22),
('Belizean', 'بيليزي', 23),
('Beninese', 'بنيني', 24),
('Saint Barthelmian', 'سان بارتيلمي', 25),
('Bermudan', 'برمودي', 26),
('Bhutanese', 'بوتاني', 27),
('Bolivian', 'بوليفي', 28),
('Bosnian Herzegovinian', 'بوسني هرسكي', 29),
('Botswanan', 'بوتسواني', 30),
('Bouvetian', 'بوفيهي', 31),
('Brazilian', 'برازيلي', 32),
('British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني', 33),
('Bruneian', 'بروني', 34),
('Bulgarian', 'بلغاري', 35),
('Burkinabe', 'بوركيني', 36),
('Burundian', 'بورونيدي', 37),
('Cambodian', 'كمبودي', 38),
('Cameroonian', 'كاميروني', 39),
('Canadian', 'كندي', 40),
('Cape Verdean', 'الرأس الأخضر', 41),
('Caymanian', 'كايماني', 42),
('Central African', 'أفريقي', 43),
('Chadian', 'تشادي', 44),
('Chilean', 'شيلي', 45),
('Chinese', 'صيني', 46),
('Christmas Islander', 'جزيرة عيد الميلاد', 47),
('Cocos Islander', 'جزر كوكوس', 48),
('Colombian', 'كولومبي', 49),
('Comorian', 'جزر القمر', 50),
('Congolese', 'كونغي', 51),
('Cook Islander', 'جزر كوك', 52),
('Costa Rican', 'كوستاريكي', 53),
('Croatian', 'كوراتي', 54),
('Cuban', 'كوبي', 55),
('Cypriot', 'قبرصي', 56),
('Curacian', 'كوراساوي', 57),
('Czech', 'تشيكي', 58),
('Danish', 'دنماركي', 59),
('Djiboutian', 'جيبوتي', 60),
('Dominican', 'دومينيكي', 61),
('Dominican', 'دومينيكي', 62),
('Ecuadorian', 'إكوادوري', 63),
('Egyptian', 'مصري', 64),
('Salvadoran', 'سلفادوري', 65),
('Equatorial Guinean', 'غيني', 66),
('Eritrean', 'إريتيري', 67),
('Estonian', 'استوني', 68),
('Ethiopian', 'أثيوبي', 69),
('Falkland Islander', 'فوكلاندي', 70),
('Faroese', 'جزر فارو', 71),
('Fijian', 'فيجي', 72),
('Finnish', 'فنلندي', 73),
('French', 'فرنسي', 74),
('French Guianese', 'غويانا الفرنسية', 75),
('French Polynesian', 'بولينيزيي', 76),
('French', 'أراض فرنسية جنوبية وأنتارتيكية', 77),
('Gabonese', 'غابوني', 78),
('Gambian', 'غامبي', 79),
('Georgian', 'جيورجي', 80),
('German', 'ألماني', 81),
('Ghanaian', 'غاني', 82),
('Gibraltar', 'جبل طارق', 83),
('Guernsian', 'غيرنزي', 84),
('Greek', 'يوناني', 85),
('Greenlandic', 'جرينلاندي', 86),
('Grenadian', 'غرينادي', 87),
('Guadeloupe', 'جزر جوادلوب', 88),
('Guamanian', 'جوامي', 89),
('Guatemalan', 'غواتيمالي', 90),
('Guinean', 'غيني', 91),
('Guinea-Bissauan', 'غيني', 92),
('Guyanese', 'غياني', 93),
('Haitian', 'هايتي', 94),
('Heard and Mc Donald Islanders', 'جزيرة هيرد وجزر ماكدونالد', 95),
('Honduran', 'هندوراسي', 96),
('Hongkongese', 'هونغ كونغي', 97),
('Hungarian', 'مجري', 98),
('Icelandic', 'آيسلندي', 99),
('Indian', 'هندي', 100),
('Manx', 'ماني', 101),
('Indonesian', 'أندونيسيي', 102),
('Iranian', 'إيراني', 103),
('Iraqi', 'عراقي', 104),
('Irish', 'إيرلندي', 105),
('Israeli', 'إسرائيلي', 106),
('Italian', 'إيطالي', 107),
('Ivory Coastian', 'ساحل العاج', 108),
('Jersian', 'جيرزي', 109),
('Jamaican', 'جمايكي', 110),
('Japanese', 'ياباني', 111),
('Jordanian', 'أردني', 112),
('Kazakh', 'كازاخستاني', 113),
('Kenyan', 'كيني', 114),
('I-Kiribati', 'كيريباتي', 115),
('North Korean', 'كوري', 116),
('South Korean', 'كوري', 117),
('Kosovar', 'كوسيفي', 118),
('Kuwaiti', 'كويتي', 119),
('Kyrgyzstani', 'قيرغيزستاني', 120),
('Laotian', 'لاوسي', 121),
('Latvian', 'لاتيفي', 122),
('Lebanese', 'لبناني', 123),
('Basotho', 'ليوسيتي', 124),
('Liberian', 'ليبيري', 125),
('Libyan', 'ليبي', 126),
('Liechtenstein', 'ليختنشتيني', 127),
('Lithuanian', 'لتوانيي', 128),
('Luxembourger', 'لوكسمبورغي', 129),
('Sri Lankian', 'سريلانكي', 130),
('Macanese', 'ماكاوي', 131),
('Macedonian', 'مقدوني', 132),
('Malagasy', 'مدغشقري', 133),
('Malawian', 'مالاوي', 134),
('Malaysian', 'ماليزي', 135),
('Maldivian', 'مالديفي', 136),
('Malian', 'مالي', 137),
('Maltese', 'مالطي', 138),
('Marshallese', 'مارشالي', 139),
('Martiniquais', 'مارتينيكي', 140),
('Mauritanian', 'موريتانيي', 141),
('Mauritian', 'موريشيوسي', 142),
('Mahoran', 'مايوتي', 143),
('Mexican', 'مكسيكي', 144),
('Micronesian', 'مايكرونيزيي', 145),
('Moldovan', 'مولديفي', 146),
('Monacan', 'مونيكي', 147),
('Mongolian', 'منغولي', 148),
('Montenegrin', 'الجبل الأسود', 149),
('Montserratian', 'مونتسيراتي', 150),
('Moroccan', 'مغربي', 151),
('Mozambican', 'موزمبيقي', 152),
('Myanmarian', 'ميانماري', 153),
('Namibian', 'ناميبي', 154),
('Nauruan', 'نوري', 155),
('Nepalese', 'نيبالي', 156),
('Dutch', 'هولندي', 157),
('Dutch Antilier', 'هولندي', 158),
('New Caledonian', 'كاليدوني', 159),
('New Zealander', 'نيوزيلندي', 160),
('Nicaraguan', 'نيكاراجوي', 161),
('Nigerien', 'نيجيري', 162),
('Nigerian', 'نيجيري', 163),
('Niuean', 'ني', 164),
('Norfolk Islander', 'نورفوليكي', 165),
('Northern Marianan', 'ماريني', 166),
('Norwegian', 'نرويجي', 167),
('Omani', 'عماني', 168),
('Pakistani', 'باكستاني', 169),
('Palauan', 'بالاوي', 170),
('Palestinian', 'فلسطيني', 171),
('Panamanian', 'بنمي', 172),
('Papua New Guinean', 'بابوي', 173),
('Paraguayan', 'بارغاوي', 174),
('Peruvian', 'بيري', 175),
('Filipino', 'فلبيني', 176),
('Pitcairn Islander', 'بيتكيرني', 177),
('Polish', 'بولندي', 178),
('Portuguese', 'برتغالي', 179),
('Puerto Rican', 'بورتي', 180),
('Qatari', 'قطري', 181),
('Reunionese', 'ريونيوني', 182),
('Romanian', 'روماني', 183),
('Russian', 'روسي', 184),
('Rwandan', 'رواندا', 185),
('Kittitian/Nevisian', 'سانت كيتس ونيفس', 186),
('St. Martian(French)', 'ساينت مارتني فرنسي', 187),
('St. Martian(Dutch)', 'ساينت مارتني هولندي', 188),
('St. Pierre and Miquelon', 'سان بيير وميكلوني', 189),
('Saint Vincent and the Grenadines', 'سانت فنسنت وجزر غرينادين', 190),
('Samoan', 'ساموي', 191),
('Sammarinese', 'ماريني', 192),
('Sao Tomean', 'ساو تومي وبرينسيبي', 193),
('Saudi Arabian', 'سعودي', 194),
('Senegalese', 'سنغالي', 195),
('Serbian', 'صربي', 196),
('Seychellois', 'سيشيلي', 197),
('Sierra Leonean', 'سيراليوني', 198),
('Singaporean', 'سنغافوري', 199),
('Slovak', 'سولفاكي', 200),
('Slovenian', 'سولفيني', 201),
('Solomon Island', 'جزر سليمان', 202),
('Somali', 'صومالي', 203),
('South African', 'أفريقي', 204),
('South Georgia and the South Sandwich', 'لمنطقة القطبية الجنوبية', 205),
('South Sudanese', 'سوادني جنوبي', 206),
('Spanish', 'إسباني', 207),
('St. Helenian', 'هيلاني', 208),
('Sudanese', 'سوداني', 209),
('Surinamese', 'سورينامي', 210),
('Svalbardian/Jan Mayenian', 'سفالبارد ويان ماين', 211),
('Swazi', 'سوازيلندي', 212),
('Swedish', 'سويدي', 213),
('Swiss', 'سويسري', 214),
('Syrian', 'سوري', 215),
('Taiwanese', 'تايواني', 216),
('Tajikistani', 'طاجيكستاني', 217),
('Tanzanian', 'تنزانيي', 218),
('Thai', 'تايلندي', 219),
('Timor-Lestian', 'تيموري', 220),
('Togolese', 'توغي', 221),
('Tokelaian', 'توكيلاوي', 222),
('Tongan', 'تونغي', 223),
('Trinidadian/Tobagonian', 'ترينيداد وتوباغو', 224),
('Tunisian', 'تونسي', 225),
('Turkish', 'تركي', 226),
('Turkmen', 'تركمانستاني', 227),
('Turks and Caicos Islands', 'جزر توركس وكايكوس', 228),
('Tuvaluan', 'توفالي', 229),
('Ugandan', 'أوغندي', 230),
('Ukrainian', 'أوكراني', 231),
('Emirati', 'إماراتي', 232),
('British', 'بريطاني', 233),
('American', 'أمريكي', 234),
('US Minor Outlying Islander', 'أمريكي', 235),
('Uruguayan', 'أورغواي', 236),
('Uzbek', 'أوزباكستاني', 237),
('Vanuatuan', 'فانواتي', 238),
('Venezuelan', 'فنزويلي', 239),
('Vietnamese', 'فيتنامي', 240),
('American Virgin Islander', 'أمريكي', 241),
('Vatican', 'فاتيكاني', 242),
('Wallisian/Futunan', 'فوتوني', 243),
('Sahrawian', 'صحراوي', 244),
('Yemeni', 'يمني', 245),
('Zambian', 'زامبياني', 246),
('Zimbabwean', 'زمبابوي', 247);
